packages:
  # all packages in direct subdirs of projects/
  - "projects/*"
  # # all packages in subdirs of components/
  # - 'components/**'
  # # exclude packages that are inside test directories
  # - '!**/test/**'
